/**
 * @description       : 
 * @author            : ChangeMeIn@UserSettingsUnder.SFDoc
 * @group             : 
 * @last modified on  : 02-21-2024
 * @last modified by  : ChangeMeIn@UserSettingsUnder.SFDoc
**/
public class DemoClass {
    public Static void copadoDemoMethod(String str){
        String var = 'Ok';
        String var2 = 'how';
		system.debug('I Am a Demo of Copado class & Method' + str + 'check');
    }
}