/**
 * @description       : 
 * @author            : ChangeMeIn@UserSettingsUnder.SFDoc
 * @group             : 
 * @last modified on  : 02-22-2024
 * @last modified by  : ChangeMeIn@UserSettingsUnder.SFDoc
**/
public class DemoClass {
    public Static void copadoDemoMethod(String str){
		system.debug('I Am Demo of Copado class & Method' + str);
    System.debug('I Am Demo of Copado class & Method' + str);
    }

}