/**
 * @description       : 
 * @author            : ChangeMeIn@UserSettingsUnder.SFDoc
 * @group             : 
 * @last modified on  : 02-20-2024
 * @last modified by  : ChangeMeIn@UserSettingsUnder.SFDoc
**/
public class DemoClass {
    public Static void copadoDemoMethod(String str){
        String var = 'Ok';
		system.debug('I Am Demo of Copado class & Method' + str);
        system.debug('I Am Demo of Copado class & Method' + str);
        
    }

}